<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="admin" failures="1" tests="5" name="Listeners Test" time="0.065" errors="0" timestamp="2022-01-29T22:25:35 IST">
  <testcase classname="Listeners.DemoListenersTest" name="test" time="0.005"/>
  <testcase classname="Listeners.DemoListenersTest" name="testFour" time="0.003">
    <skipped/>
  </testcase> <!-- testFour -->
  <testcase classname="Listeners.DemoListenersTest" name="testGetData" time="0.005"/>
  <testcase classname="Listeners.DemoListenersTest" name="testGetData" time="0.004"/>
  <testcase classname="Listeners.DemoListenersTest" name="testThree" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at Listeners.DemoListenersTest.testThree(DemoListenersTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testThree -->
</testsuite> <!-- Listeners Test -->
